apiVersion: v2
name: microservice
version: 0.1.0
description: A Helm chart for deploying the microservice

dependencies:
  - name: postgresql
    version: 12.1.3
    repository: "https://charts.bitnami.com/bitnami"
