stages:
  - lint
  - test
  - cpipe/preprocess
  - cpipe/preflight
  - cpipe/lint
  - cpipe/build
  - cpipe/sign
  - cpipe/scan
  - cpipe/validate_CIS
  - cpipe/publish
  - cpipe/tag
  - version
  - release
  - deploy

include:
  - project: 'chimera/container-pipeline'
    ref: v1.0.3
    file: '/templates/default.yaml'

  - component: $CI_SERVER_FQDN/DevOps/cde/templates-examples/cde-components/automatic-versioning@v1.1.9
    inputs:
      enable_auto_versioning: true
      enable_gitlab_release: false
      branch_regex: main

variables:
  CPIPE_DOCKERFILE: Dockerfile

  CONTAINER_REG_HARBOROP_HOST: https://harbor.xcr.svcs01.prod.wv.kaas.sws.siemens.com/
  CONTAINER_REG_HARBOROP_USER: robot$$oat+cicd
  CONTAINER_DEST_HARBOROP_PATH: harbor.xcr.svcs01_
