apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: {{ .Values.microservice.service.port }}
      targetPort: {{ .Values.microservice.service.port }}
  type: {{ .Values.microservice.service.type | default "ClusterIP" }}
